{{- $chartName := include "export-management.name" . -}}
{{- $tracingUrl := include "export-management.tracingUrl" . -}}
{{- $metricsUrl := include "export-management.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_SHOULD_RESET_TIMEOUT: {{ .Values.env.httpRetry.shouldResetTimeout | quote }}
  DISABLE_HTTP_CLIENT_LOGS: {{ .Values.env.disableHttpClientLogs | quote }}
  {{- with .Values.db }}
  DB_HOST: {{ .host }}
  DB_NAME: {{ .database }}
  DB_SCHEMA: {{ .schema }}
  DB_PORT: {{ .port | default 5432 | quote }}
  {{- if .sslAuth.enabled }}
  DB_ENABLE_SSL_AUTH: "true"
  DB_CERT_PATH: /tmp/certs/{{ .sslAuth.certFileName }}
  DB_KEY_PATH: /tmp/certs/{{ .sslAuth.keyFileName }}
  DB_CA_PATH: /tmp/certs/{{ .sslAuth.caFileName }}
  {{- else }}
  DB_ENABLE_SSL_AUTH: "false"
  {{- end }}
  {{- end }}
  MAX_TASKS_NUMBER: {{ .Values.env.maxTasksNumber | quote }}
{{- end }}
