{{- $chartName := include "export-management.name" . -}}
{{- $tracingUrl := include "export-management.tracingUrl" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $metricsUrl := include "export-management.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_SHOULD_RESET_TIMEOUT: {{ .Values.env.httpRetry.shouldResetTimeout | quote }}
  DISABLE_HTTP_CLIENT_LOGS: {{ .Values.env.disableHttpClientLogs | quote }}
  SERVICE_WEBHOOK_ENDPOINT:  {{ .Values.env.serviceWebhookEndpoint | quote }}
  EXPORTER_TRIGGER_URL: {{ .Values.serviceUrls.exporterTrigger  | quote }}
  JOB_MANAGER_URL: {{ .Values.serviceUrls.jobManager  | quote }}
  JOB_MANAGER_EXPORT_JOB_TYPE: {{ .Values.jobManagement.exporter.jobType | quote }}
  AUTH_ENABLED: {{ .Values.nginx.authorization.domain | quote }}
  {{ if and (not .Values.nginx.opalaEnabled) (.Values.nginx.authorization.domain) }}
  AUTH_VALID_DOMAIN: {{ .Values.nginx.authorization.domain | quote }}
  AUTH_HEADER_NAME: {{ .Values.nginx.opa.customHeaderName | quote }}
  AUTH_QUERY_NAME: {{ .Values.nginx.authorization.token.queryName | quote }}
  {{- end}}
{{- end }}
