apiVersion: v2
name: common-export-management
description: A Helm chart for export-management service
type: application
version: 1.4.1
appVersion: 1.4.1
dependencies:
  - name: nginx
    version: 1.1.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
