global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}
  authentication:
    jwtPublicKeySecretName: map-colonies-jwks

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true
imagePullPolicy: Always

cloudProvider:
  dockerRegistryUrl: acrarolibotnonprod.azurecr.io
  imagePullSecretName: 'acr-registry'
  flavor: openshift

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

image:
  repository: export-management
  tag: 'v1.1.4'

serviceUrls:
  exporterTrigger: "http://exporter-trigger-raster-qa-exporter-trigger/"
  jobManager: "http://job-manager-raster-qa-job-manager/"
jobManagement:
  exporter:
    jobType: rasterTilesExporter
authentication:
  opa:
    enabled: true
    customHeaderName: "x-api-key"


env:
  port: 8080
  internalPort: 80
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  disableHttpClientLogs: false
  #https://exoprt-management-no-auth-integration.apps.j1lk3njp.eastus.aroapp.io/export-tasks/webhook
  serviceWebhookEndpoint: http://export-management-export-management/export-tasks/webhook
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  httpRetry:
    attempts: 5
    delay: exponential
    shouldResetTimeout: true

opa:
  image: openpolicyagent/opa
  imageTag: 0.29.4-envoy-3
  port: 9191
  enableLogging: false
  resources:
    enabled: false
    value:
      limits:
        cpu: 250m
        memory: 150Mi
      requests:
        cpu: 250m
        memory: 150Mi
        
envoy:
  image: envoyproxy/envoy
  imageTag: v1.20.7
  port: 8000
  maxRequestBytes: 8192
  requestedDomain: rasterExport
  resources:
    enabled: false
    value:
      limits:
        cpu: 500m
        memory: 850Mi
      requests:
        cpu: 500m
        memory: 850Mi

  

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  host:
  path: /api/raster/v1
  https: true
  useCert: false
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)

ingress:
  enabled: false
  type: 'nginx-org' # supported values: 'nginx-org' | 'nginx-kubernetes
  tls:
    enabled: false
    useExternal: ''
  path: /api/raster/v1
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
